# Generated by Django 5.0.14 on 2026-09-20 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('selecione', 'selecione'), ('cuerda', 'Cuerda'), ('viento', 'Viento'), ('percusion', 'Percusion'), ('teclado', 'Teclado')], default='selecione', max_length=50)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('marca', models.CharField(choices=[('selecione', 'selecione'), ('yamaha', 'Yamaha'), ('fender', 'Fender'), ('gibson', 'Gibson'), ('roland', 'Roland'), ('otra', 'Otra')], default='selecione', max_length=50)),
            ],
        ),
    ]
