# Generated by Django 5.0.14 on 2026-09-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentos',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
    ]
