# Generated by Django 5.0.14 on 2026-09-22 05:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicAPP', '0002_alter_instrumentos_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentos',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='instrumentos',
            name='marca',
            field=models.CharField(choices=[('yamaha', 'Yamaha'), ('fender', 'Fender'), ('gibson', 'Gibson'), ('roland', 'Roland'), ('otra', 'Otra')], max_length=50),
        ),
        migrations.AlterField(
            model_name='instrumentos',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='instrumentos',
            name='precio',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='instrumentos',
            name='tipo',
            field=models.CharField(choices=[('cuerda', 'Cuerda'), ('viento', 'Viento'), ('percusion', 'Percusion'), ('teclado', 'Teclado')], max_length=50),
        ),
    ]
