# Generated by Django 5.0.14 on 2026-09-22 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicAPP', '0003_alter_instrumentos_cantidad_alter_instrumentos_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentos',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
    ]
