# Generated by Django 5.0.14 on 2026-09-22 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicAPP', '0004_alter_instrumentos_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentos',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2000)]),
        ),
    ]
